CREATE TABLE products
(
    id          VARCHAR NOT NULL PRIMARY KEY,
    name        VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    price       DECIMAL NOT NULL,
    quantity    INTEGER NOT NULL,
    image       VARCHAR NOT NULL
);

INSERT INTO products (id, name, description, price, quantity, image)
values ('bde4667a-e422-41c8-93c4-fc5754fc2e6a', 'Labial Maybelline',
        'Labial de larga duración con una amplia gama de colores para lucir labios hermosos.', 150, 10,
        '../../Recursos/Productos/labial.png'),
       ('bde4667a-e422-41c8-93c4-fc5754fc2e6c', 'Base Mary Kay',
        'Base de maquillaje de alta calidad para una piel perfecta y natural.', 200, 10,
        '../../Recursos/Productos/base mary kay.png'),
       ('bde4667a-e422-41c8-93c4-fc5754fc2e6d', 'Corrector Maybelline',
        'Corrector líquido para ocultar imperfecciones y lograr una piel impecable.', 200, 10,
        '../../Recursos/Productos/corrector.png'),
       ('bde4667a-e422-41c8-93c4-fc5754fc2e6e', 'Esmalte para uñas Bisuu',
        'Esmalte de uñas de colores vibrantes y duraderos para unas manos perfectas.', 300, 10,
        '../../Recursos/Productos/esmalte uñas.png'),
       ('bde4667a-e422-41c8-93c4-fc5754fc2e6f', 'Polvo NYC',
        'Polvo compacto para fijar el maquillaje y matificar la piel durante todo el día.', 200, 10,
        '../../Recursos/Productos/polvo.png'),
       ('bde4667a-e422-41c8-93c4-fc5754fc2e6g', 'Rimel Mary Kay',
        'Rímel para pestañas más largas y voluminosas que realzan tu mirada.', 200, 10,
        '../../Recursos/Productos/rimel.png'),
       ('bde4667a-e422-41c8-93c4-fc5754fc2e6h', 'Rubor Bisuu',
        'Rubor en polvo de colores encantadores para darle vida a tus mejillas.', 200, 10,
        '../../Recursos/Productos/rubor.png'),
       ('bde4667a-e422-41c8-93c4-fc5754fc2e6i', 'Tinte LOreal Paris',
        'Tinte para el cabello de calidad profesional para un color intenso y duradero.', 200, 10,
        '../../Recursos/Productos/tinte.png'),
       ('bde4667a-e422-41c8-93c4-fc5754fc2e6j', 'Base Fit Me',
        'Base de maquillaje líquida que se adapta perfectamente a tu tono de piel.', 200, 10,
        '../../Recursos/Productos/base.png'),
       ('bde4667a-e422-41c8-93c4-fc5754fc2e6k', 'Cepillo Revlon',
        'Cepillo de alta calidad para desenredar y peinar tu cabello con facilidad.', 150, 10,
        '../../Recursos/Productos/cepillo.png');